machines/urls.py
from django.conf.urls import url

from . import views

app_name='machines'
urlpatterns = [
    # ex: /machines/
    url(r'^$', views.index, name='index'),
    # ex: /machines/signin/
    url(r'^signin/$', views.signin, name='signin'),
    # ex: /machines/signup/
    url(r'^signup/$', views.signup, name='signup'),
    # ex: /machines/setup/
    url(r'^setup/$', views.setup, name='setup'),
    # ex: /machines/progress/
    url(r'^progress/$', views.progress, name='progress'),
]

mywebsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^machines/', include('machines.urls')),
    url(r'^admin/', admin.site.urls),
]

machines/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible


# Create your models here.

@python_2_unicode_compatible
class Machine(models.Model):
    hostname = models.CharField(max_length=200)

    ARCHS = (
        ('sparc', 'sparc platform'),
        ('i386', 'x86 platform'),
    )
    arch = models.CharField(max_length=5, choices=ARCHS)

    location = models.CharField(max_length=10)

    STATUS = (
        ('A', 'available'),
        ('R', 'reserved'),
    )
    status = models.CharField(max_length=1, choices=STATUS)
    user = models.ForeignKey(User)
    note = models.TextField()

    def __str__(self):
        return self.hostname    


@python_2_unicode_compatible
class OS(models.Model):
   pass 

machines/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'machines/index.html')

def signin(request):
    return render(request, 'machines/signin.html')

def signup(request):
    return render(request, 'machines/signup.html')

def setup(request):
    return render(request, 'machines/setup.html')

def progress(request):
    return render(request, 'machines/progress.html')

machines/templates/machines/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% block title %}
    <title>Here is your title</title>
    {% endblock %}

    <!-- Bootstrap -->
    <link href="{% static 'machines/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- here for IE8, IE9 and IE10 compatible -->
  </head>

  <body>
    <div class="container">
    {% block content %}  
    <h1>Hello, world!</h1>
    {% endblock %}
    </div>
    <!-- jQuery (necessary for Bootstrap's Javascript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins, or include individual files as needed -->
  </body>
</html>

machines/templates/machines/index.html
{% extends "machines/base.html" %}

{% block title %}
<title>Index Page</title>
{% endblock %}


{% block content %}
<h1>Home Page</h1>
<hr />
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <p> To use this system, you need to <a href="{% url 'machines:signin' %}">Signin</a>.</p>
    <p> If you have no an account, please click <a href="{% url 'machines:signup' %}">here</a> to get one.</p>
  </div>
</div>
{% endblock %}

machines/templates/machines/progress.html
{% extends "machines/base.html" %}

{% block title %}
<title>Progress Page</title>
{% endblock %}

{% block content %}
<h1> Here is the Progress Page.</h1>
{% endblock %}

machines/templates/machines/setup.html
{% extends "machines/base.html" %}

{% block title %}
<title>Setup Page</title>
{% endblock %}

{% block content %}
<h1> Here is the Setup Page.</h1>
<hr />

{% endblock %}

machines/templates/machines/signin.html
{% extends "machines/base.html" %}

{% block title %}
<title>Signin Page</title>
{% endblock %}

{% block content %}
<h1> Here is the SignIn Form.</h1>
<hr />
<form class="form-horizontal" action="{% url 'machines:signin' %}" method="post">
{% csrf_token %}
  <div class="form-group">
    <label for="inputUser" class="col-md-2 control-label">Username</label>
    <div class="col-md-10">
      <input class="form-control" id="inputUser" type="text" name="username" placeholder="Your Username" />
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword" class="col-md-2 control-label">Password</label>
    <div class="col-md-10">
      <input class="form-control" id="inputPassword" type="text" name="password" placeholder="Your Password" />
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-10">
	    <div class="checkbox">
		    <label><input type="checkbox"> Remember me </label>
	    </div>
    </div>
  </div>
  <div class="form-group">
	  <div class="col-md-offset-2 col-md-10">
		  <button type="submit" class="btn btn-default">Sign In</button>
	  </div>
  </div>
</form>
{% endblock %}

machines/templates/machines/signup.html
{% extends "machines/base.html" %}

{% block title %}
<title>Signin Page</title>
{% endblock %}

{% block content %}
<h1> Here is the SignIn Form.</h1>
<hr />
<form class="form" action="{% url 'machines:signin' %}" method="post">
{% csrf_token %}
  <input class="form-control" type="text" name="username" placeholder="Your Username" />
  <input class="form-control" type="password" name="password" placehoder="Your Password" />
  <button class="btn btn-primary" type="submit" >Sign In</button>
</form>
{% endblock %}